name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4
      with: 
        fetch-depth: 0
        
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Iniciando login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Finalizando login"
        
    - name: Build Docker Image
      run: |
        docker build -t ghost1975/docker-graphql:0.0.2 . 
        
    - name: Push Docker Image
      run: |
        docker push ghost1975/doocker-graphql:0.0.2 



    
        
        
        
    
    
#    - name: Build the Docker image
#       docker build . --file Dockerfile --tag my-image-name:$(date +%s)
