name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
        
      - name: Git Semantic Version
        id: version
        uses: PaulHatch/semantic-version@v4.0.3
        with:
          major_pattern: "major:"
          minor_pattern: "feat:"
          format: "${major}.${minor}.${patch}-prereleases${increment}"
        
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Images
        run: |
          docker build -t ghost1975/docker-graphql:${{ steps.version.outputs.version }} .
          docker build -t ghost1975/docker-graphql:latest .

      - name: Push Docker Images
        run: |
          docker push ghost1975/docker-graphql:${{ steps.version.outputs.version }}
          docker push ghost1975/docker-graphql:latest

        
    
    
#    - name: Build the Docker image
#       docker build . --file Dockerfile --tag my-image-name:$(date +%s)
